version: "3.9"
services:
  api:
    build: .
    container_name: task-manager-api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:////data/tasks.db
    volumes:
      - appdata:/data
volumes:
  appdata:
